### ISSUE TITLE
다시 제작 예정

### ISSUE THREAD

**Issue by surplus-dev** [2du/JS-openNAMUmark#8]
생각보다 여기서 개발한 알고리즘이 쓸모가 있어서 개발할 예정

**Comment by wbmltd** [comment]
안녕하세요 요즘 나무위키가 광고를 너무 많이 부착하는게 마음에 안들어 새로운 위키를 찾고 있는데 오프나무 제대로 성장시킬 계획이신가 궁금해서 여기에 글 남깁니다~

**Comment by surplus-dev** [comment]
@wbmltd 오픈나무는 위키 엔진이지 위키가 아닙니다

**Comment by surplus-dev** [comment]
재개발 시작
